checks:
    php: true

filter:
    excluded_paths:
        - "tests/"
        - "var/"
    dependency_paths:
        - "vendor/"

build:
    nodes:
        analisys:
            environment:
                php: "7.1"

            tests:
                override:
                  - php-scrutinizer-run
                  -
                    command: vendor/bin/codecept run unit --coverage --coverage-xml -f --debug
                    coverage:
                        file: tests/_output/coverage.xml
                        format: php-clover
