language: php

php:
  - 7.1.13

sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

#services:
#  - 'redis_server'

  
before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --optimize-autoloader

script:
  - vendor/bin/codecept run unit --coverage --coverage-text --coverage-xml -f --debug