tasks:
  init:
    classname: \PlanB\Wand\Core\Task\SimpleTask
    description: wubba lubba dub dub
    actions:
      readme:
        group: metainfo
        classname: \PlanB\Wand\Core\File\File
        params:
          template: '@wand.metainfo.readme.twig'
          target: README.md
          action: override # delete, create
          chmod: 0644
      license:
        group: metainfo
        classname: \PlanB\Wand\Core\File\File
        params:
          template: '@wand.metainfo.readme.twig'
          target: README.md
          action: override # delete, create
          chmod: 0644
